######################## general API calls ########################

# POST https://genericweb.onrender.com/api/v1/auth/login/
POST {{$dotenv NGROK_URL}}/api/v1/auth/login/
Content-Type: application/json

# {
#     "email": "clinicManager1@example.com",
#     "password": "a123456!"
# }

# {
#     "email": "doctor1@example.com",
#     "password": "a123456!"
# }

# {
#     "email": "ozeriyarin@gmail.com",
#     "password": "a123456!"
# }

###

POST {{$dotenv NGROK_URL}}/api/v1/auth/logout/
Content-Type: application/json

########################### modules API calls ###########################

POST {{$dotenv NGROK_URL}}/api/v1/modules/add/
Content-Type: application/json
Authorization: Token 3439658e926edbe9c73c7b5b753371ce01a80139

{
    "module_name": "New Module"
}

###

DELETE {{$dotenv NGROK_URL}}/api/v1/modules/9/delete/
Content-Type: application/json
Authorization: Token 3439658e926edbe9c73c7b5b753371ce01a80139

############################ users api calls ############################

GET {{$dotenv NGROK_URL}}/api/v1/users/1/3/
Content-Type: application/json

###

GET {{$dotenv NGROK_URL}}/api/v1/users/3/

###

GET {{$dotenv NGROK_URL}}/api/v1/users/3/qr-code/

###

POST https://genericweb.onrender.com/api/v1/users/1/add/
Content-Type: application/json

{
    "email": "patient4@example.com",
    "first_name": "patient4",
    "last_name": "example",
    "phone_number": "0534567893",
    "password": "a123456!",
    "confirm_password": "a123456!"
}

###

PUT {{$dotenv NGROK_URL}}/api/v1/users/3/update/
Content-Type: application/json

{
    "email": "doctor1@example.com",
    "first_name": "doctor1",
    "last_name": "example",
    "phone_number": "1234567890"
}

###

DELETE {{$dotenv NGROK_URL}}/api/v1/users/1/3/remove/
Content-Type: application/json

###

############################ clinics api calls ############################

GET {{$dotenv NGROK_URL}}/api/v1/clinics/

###

GET {{$dotenv NGROK_URL}}/api/v1/clinics/1/

### 

POST {{$dotenv NGROK_URL}}/api/v1/clinics/add/
Content-Type: application/json

{
    "clinic_name": "clinictest",
    "clinic_url": "https://clinictest.com",
    "manager_first_name": "clinicManagertest1",
    "manager_last_name": "example",
    "manager_email": "clinicManagertest1@example.com",
    "manager_phone_number": "0502345673",
    "clinic_type": "Research",
    "clinic_image_url": "",
    "selected_modules": [1, 2, 3,4,5]
}

###

PUT {{$dotenv NGROK_URL}}/api/v1/clinics/3/update/
Content-Type: application/json

{
    "clinic_name": "clinic3",
    "clinic_url": "https://clinic3.com",
    "clinic_type": "Research",
    "clinic_image_url": "",
    "selected_modules": [1, 2, 3, 4, 5]
}

###

DELETE {{$dotenv NGROK_URL}}/api/v1/clinics/7/delete/
Content-Type: application/json


############################ medications api calls ############################

GET {{$dotenv NGROK_URL}}/api/v1/medications/
Content-Type: application/json

###

POST {{$dotenv NGROK_URL}}/api/v1/medications/add/
Content-Type: application/json

{
    "id": "3000000809",
    "medName": "Aspirin",
    "medForm": "pill",
    "medUnitOfMeasurement": "mg"
}

###

PUT {{$dotenv NGROK_URL}}/api/v1/medications/update/3000000809/
Content-Type: application/json

{
    "id": "3000000809",
    "medName": "Aspirin Updated",
    "medForm": "pill",
    "medUnitOfMeasurement": "mg"
}

###

DELETE {{$dotenv NGROK_URL}}/api/v1/medications/delete/3000000809/
Content-Type: application/json

###

GET {{$dotenv NGROK_URL}}/api/v1/medications/clinic/1/
Content-Type: application/json


###

POST {{$dotenv NGROK_URL}}/api/v1/medications/clinic/7/add/
Content-Type: application/json

{
    "med_id": "1999022181"
}


###

DELETE {{$dotenv NGROK_URL}}/api/v1/medications/clinic/1/delete/1999022181/
Content-Type: application/json

### 

GET {{$dotenv NGROK_URL}}/api/v1/medications/patient/1/5/
Content-Type: application/json

###

POST {{$dotenv NGROK_URL}}/api/v1/medications/patient/1/5/add/
Content-Type: application/json

# {
#     "med_id": "1999022181",
#     "frequency" : "weekly",
#     "frequency_data": {
#         "dates": [],
#         "days": ["monday", "wednesday", "friday"],
#         "time": ["10:00", "14:00"]
#     },
#     "start_date": "2025-07-01",
#     "end_date": "2025-07-31",
#     "dosage": "pill"
# }

{
    "med_id": "1000000809",
    "frequency" : "monthly",
    "frequency_data": {
        "dates": ["2025-07-01", "2025-07-08", "2025-07-15"],
        "days": [],
        "time": ["10:00", "14:00"]
    },
    "start_date": "2025-07-01",
    "end_date": "2025-07-31",
    "dosage": "pill"
}

###

PUT {{$dotenv NGROK_URL}}/api/v1/medications/patient/1/5/update/
Content-Type: application/json

# {
#     "med_id": "1999022181",
#     "frequency" : "weekly",
#     "frequency_data": {
#         "dates": [],
#         "days": ["monday", "wednesday", "friday"],
#         "time": "11:00"
#     },
#     "start_date": "2025-07-01",
#     "end_date": "2025-07-31",
#     "dosage": "TAB"
# }

{
    "med_id": "1000000809",
    "frequency" : "monthly",
    "frequency_data": {
        "dates": ["2025-07-01", "2025-07-08", "2025-07-15"],
        "days": [],
        "time": ["10:00", "14:00"]
    },
    "start_date": "2025-07-01",
    "end_date": "2025-07-31",
    "dosage": "pill"
}

###

DELETE {{$dotenv NGROK_URL}}/api/v1/medications/patient/1/5/delete/1999022181/
Content-Type: application/json

###

POST {{$dotenv NGROK_URL}}/api/v1/medications/report/
Content-Type: application/json

{
  "clinic_id": 1,
  "patient_id": 5,
  "medication_id": "1999022181",
  "timestamp": "2025-08-10 11:00:00"
}

###

GET {{$dotenv NGROK_URL}}/api/v1/medications/patient/1/5/log/
Content-Type: application/json

########################### activities api calls ###########################

GET {{$dotenv NGROK_URL}}/api/v1/activities/
Content-Type: application/json

###

POST {{$dotenv NGROK_URL}}/api/v1/activities/add/
Content-Type: application/json

{
    "name": "New Activity",
    "description": "This is a new activity."
}

###

PUT {{$dotenv NGROK_URL}}/api/v1/activities/update/7/
Content-Type: application/json

{
    "name": "Updated Activity",
    "description": "This is an updated activity."
}

###

DELETE {{$dotenv NGROK_URL}}/api/v1/activities/delete/7/
Content-Type: application/json

###

GET {{$dotenv NGROK_URL}}/api/v1/activities/clinic/1/
Content-Type: application/json
###

POST {{$dotenv NGROK_URL}}/api/v1/activities/clinic/1/add/
Content-Type: application/json
Authorization: Token 5eb65ebc949c894ef65548360820548b553f5010

{
    "activity_id": 7
}

###

DELETE {{$dotenv NGROK_URL}}/api/v1/activities/clinic/1/delete/1/
Content-Type: application/json

### 

GET {{$dotenv NGROK_URL}}/api/v1/activities/patient/1/5/
Content-Type: application/json

###

POST {{$dotenv NGROK_URL}}/api/v1/activities/patient/1/5/add/
Content-Type: application/json

{
    "activity_id": 7
}

### 

DELETE {{$dotenv NGROK_URL}}/api/v1/activities/patient/1/5/delete/1/
Content-Type: application/json

### 

POST {{$dotenv NGROK_URL}}/api/v1/activities/report/
Content-Type: application/json
Authorization: Token 5eb65ebc949c894ef65548360820548b553f5010

{
    "clinic_id": 1,
    "patient_id": 5,
    "activity_id": 3,
    "timestamp": "2025-07-15 13:00:00"
}

###

############################# notifications API calls ##############################

POST {{$dotenv NGROK_URL}}/api/v1/notifications/set/notification/
Content-Type: application/json

{
  "clinic_id": 1,
  "patient_id": 5,
  "event_type": "activity",
  "event_id": "3",
  "frequency": "weekly",
    "frequency_data": {
        "dates": [],
        "days": ["monday", "wednesday", "friday"],
        "time": ["08:30", "12:00"]
    },
  "start_date_time": "2025-07-01 08:00:00",
  "end_date_time": "2025-08-01 08:00:00"
}

############################ fileshare api calls ############################

GET {{$dotenv NGROK_URL}}/api/v1/fileshare/files/1/5/

###

POST {{$dotenv NGROK_URL}}/api/v1/fileshare/files/1/5/add/
Content-Type: application/json

{
    "doctor_id": 1,
    "file": "file_content"
}

###

DELETE {{$dotenv NGROK_URL}}/api/v1/fileshare/files/1/5/delete/1/
Content-Type: application/json